### ISSUE TITLE
Dashboard status says "offline" but is working

### ISSUE THREAD

**Issue by weitzner** [juampe/docker-pi-hole-dot#5] opened 2022-02-03 22:41 UTC
The dashboard has a status of "offline" but everything seems to be working. 

<img width="230" alt="Screen Shot 2022-02-03 at 3 44 14 PM" src="https://user-images.githubusercontent.com/464597/152441759-d809e469-069d-4903-87bf-bfe01bd096f3.png">

Connecting to the container and checking out `/etc/sudoers.d/pihole` shows the same formatting as described [here](https://discourse.pi-hole.net/t/status-is-offline-but-everything-is-working/52583/14), but I am unsure if that is something that can be changed here or needs to be looked into upstream.

**Comment by weitzner** [comment] 2022-02-08 20:53
Seems to still be broken - I'll check in with upstream

**Comment by juampe** [comment] 2022-02-08 21:10
My setup seems to be active 
![imagen](https://user-images.githubusercontent.com/365683/153075950-4db345c3-737e-4e1a-864f-d7216faeeab3.png)
![imagen](https://user-images.githubusercontent.com/365683/153076025-2227fda6-6be0-4786-ad46-600f073c4ab4.png)

**Comment by juampe** [comment] 2022-02-08 21:24
As described in your link, my actual setup have this sudo file and seems to work without "special spaces" 

```
root@pihole:/# cat /etc/sudoers.d/pihole
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Allows the WebUI to use Pi-hole commands
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.
#
www-data ALL=NOPASSWD: /usr/local/bin/pihole

```

**Comment by juampe** [comment] 2022-02-08 21:30
As described in your link, my actual setup have this sudo file and seems to work without "special spaces" 

```
root@pihole:/# cat /etc/sudoers.d/pihole
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Allows the WebUI to use Pi-hole commands
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.
#
www-data ALL=NOPASSWD: /usr/local/bin/pihole

```


But the diference was huge
My setup
```
root@pihole:/# sudo -u www-data sudo pihole status web
1
root@pihole:/# 

```

edge
```
root@pihole:/# sudo -u www-data sudo pihole status web

root@pihole:/# 
```

**Comment by juampe** [comment] 2022-02-08 21:40
AFAIK the regression is in this commit
https://github.com/pi-hole/pi-hole/commit/ef30a85afb1653df4d3ce393dd6b8d7ecbb29ab0

**Comment by weitzner** [comment] 2022-02-09 00:14
Oh interesting!

**Comment by PromoFaux** [comment] 2022-02-09 07:35
I've not looked deeply into this yet, but AFAIK this is not an upstream issue - as I don't see it in our nightly or Dev containers (or even bare metal)

I suspect the issue may lie in how your image switches branches on the components but... I'll take a look after work!

**Comment by PromoFaux** [comment] 2022-02-09 07:35
I've not looked deeply into this yet, but AFAIK this is not an upstream issue - as I don't see it in our nightly or Dev containers (or even bare metal)

I suspect the issue may lie in how your image switches branches on the components but... I'll take a look after work!

**Comment by juampe** [comment] 2022-02-09 08:29
Some additional test
add debug to script in edge
```
#!/usr/bin/env bash
set -xe
----8<----
+ case "${1}" in
+ statusFunc web
+ local listening pid port
++ getFTLPID
++ local pid
++ '[' -s /run/pihole-FTL.pid ']'
++ pid=508
++ [[ 508 =~ [^[:digit:]] ]]
++ echo 508
+ pid=508
+ [[ 508 -eq -1 ]]
++ echo '>dns-port >quit'
++ nc 127.0.0.1 4711
+ port=
+ [[ '' == \0 ]]
+ [[ web != \w\e\b ]]
+ grep -q BLOCKING_ENABLED=false /etc/pihole/setupVars.conf
+ grep -q BLOCKING_ENABLED=true /etc/pihole/setupVars.conf
+ case "${1}" in
+ echo ''

```

I see that the status changes using the enable/disable bloking buttom, an the onwknow status doesn't appear anymore
![imagen](https://user-images.githubusercontent.com/365683/153154640-02e491de-08dd-4d97-8650-8c48d8a50e0b.png)

![imagen](https://user-images.githubusercontent.com/365683/153154768-7d97e0d0-26a2-4c43-a6af-915590cb88db.png)

Now the BLOCKING_ENABLED is in the  /etc/pihole/setupVars.conf file.
I can conclude that the lack of status is due to the environment variable in the configuration file (BLOCKING_ENABLED)
To fix in our work we can recomend to set BLOCKING_ENABLED as environment in the container process run.

**Comment by PromoFaux** [comment] 2022-02-09 08:51
Ah wait, this rings a bell...

It should [already be fixed](https://github.com/pi-hole/pi-hole/pull/4585) in the `development` branch of Pi-hole core ----repository (and thus should be fixed in the `nightly` image of Pi-hole docker which pulls in all the dev branches.

---

Just as a secondary point here (and maybe it is worth a new issue ) I'm not sure I understand why you are re-downloading FTL as in each of your Dockerfiles - the upstream image is multiarch and already contains the correct binary.  It appears that, maybe unintentionaly, in your nightly image you are overwriting the dev version of FTL with the released one. Same goes for the other components in the `edge` version

 - `pihole/pihole:nightly` already has the development versions of each core component checked out, shouldn't need to do anything here
 - `pihole/pihole:dev` uses only the dev branch from `docker-pi-hole` repository, but otherwise the core components are the currently released versions
 - `pihole/pihole:latest` is the `master` branch of `docker-pi-hole`, and the released versions of everything else.

**Comment by juampe** [comment] 2022-02-09 09:09
OK, we trust in upstream containers, so as you commented is not necesary update from git.
I disabled the update scripts to respect the upstream release decisions.

**Comment by PromoFaux** [comment] 2022-02-09 11:05
To the title issue, however, I don't think your solution will work :)

There is nothing in the upstream to parse the env var `BLOCKING_ENABLED`. When was the last time your containers were built? The only one that it should have been an issue in was `edge` and `nightly`, but the fix to add `BLOCKING_ENABLED` if it did not already exist was added into the core repo last week sometime.. so I'd be interested if you were still able to reproduce it with all the latest changes :)

**Comment by juampe** [comment] 2022-02-09 12:00
Thanks, let's go to some deep insight.
I triggered the github action an hour ago, and new edge is built.
The status function seems not to handle right the situation

```
root@pihole:/# cat /etc/pihole/GitHubVersions
v5.8.1 v5.10.1 v5.13
root@pihole:/#
root@pihole:/# cat /etc/pihole/setupVars.conf|grep BLOCK
BLOCKING_ENABLED=true
root@pihole:/# pihole status web

root@pihole:/#
```
DEBUG RUN
```
+ [[ 2 = 0 ]]
+ case "${1}" in
+ [[ ! 0 -eq 0 ]]
+ case "${1}" in
+ statusFunc web
+ local listening pid port
++ getFTLPID
++ local pid
++ '[' -s /run/pihole-FTL.pid ']'
++ pid=501
++ [[ 501 =~ [^[:digit:]] ]]
++ echo 501
+ pid=501
+ [[ 501 -eq -1 ]]
++ echo '>dns-port >quit'
++ nc 127.0.0.1 4711
+ port=
+ [[ '' == \0 ]]
+ [[ web != \w\e\b ]]
+ grep -q BLOCKING_ENABLED=false /etc/pihole/setupVars.conf
+ grep -q BLOCKING_ENABLED=true /etc/pihole/setupVars.conf
+ case "${1}" in
+ echo ''
  <-\n @THE STATUS RETURN NOTHING
root@pihole:/#
```

In my run, the line 330 does no return the port, so in line 355 returns nothing
```
#get the port pihole-FTL is listening on by using FTL's telnet API
    port="$(echo ">dns-port >quit" | nc 127.0.0.1 4711)"
```

Some additional netcat tests, tah itself retusn nothing
```

root@pihole:/# netstat -putan|head
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:35887        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8953          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:5353            0.0.0.0:*               LISTEN      -

root@pihole:/#  echo ">dns-port >quit" | nc 127.0.0.1 4711
root@pihole:/#
root@pihole:/# echo ">dns-port >quit" | nc 127.0.0.1 4711 |echo $?
0
root@pihole:/#
```

And to finish some suggestion/fix go get something useful
`    port="$(echo ">dns-port >quit" | nc 127.0.0.1 4711|echo $?)"`

TEST RUN
```
root@pihole:/# pihole status web
1
root@pihole:/#
```
And the status come active again
![imagen](https://user-images.githubusercontent.com/365683/153196702-446c7782-4c01-4ea0-9fba-14ef0bdd9724.png)

**Comment by PromoFaux** [comment] 2022-02-09 13:19
Your [`edge` tag is based on our `dev` tag](https://github.com/juampe/docker-pi-hole-dot/blob/master/Dockerfile.edge#L1) which, in turn has the _release_ versions of the Pi-hole, which do not contain the aforementioned PR that fixes the check for the case of a missing `BLOCKING_ENABLED`

Do you still see this issue in your `nightly` tag?

**Comment by juampe** [comment] 2022-02-09 13:45
I see the issue in the nightly tag
![imagen](https://user-images.githubusercontent.com/365683/153213025-5d10112b-ccbf-4059-b43d-878b5149d51f.png)
![imagen](https://user-images.githubusercontent.com/365683/153213184-f72e4521-8cd1-49c8-85d9-867f0b8badad.png)
```

root@pihole:/# pihole status web

root@pihole:/#
root@pihole:/etc/pihole# cat /etc/lighttpd/conf-enabled/15-fastcgi-php.conf|grep DOCKER
                        "PIHOLE_DOCKER_TAG" => "nightly",
root@pihole:/#
```

**Comment by PromoFaux** [comment] 2022-02-09 13:54
Hummm. The only thing I can see here that _might_ (not certain here as I'm working on theory!) be causing an issue. According to your version footer there, both Pi-hole core and Web are on the dev branches - but FTL is just on the mainstream v5.11 release.

I am not seeing the same issue on the latest upstream `:nightly` with the following versions

![image](https://user-images.githubusercontent.com/1998970/153215077-9073dbb3-86ca-4611-9333-7d69b0601275.png)

**Comment by juampe** [comment] 2022-02-09 14:29
OK, sorry was my fault, I forgot commit changes to not update from git.
The nightly and edge/dev are OK
![imagen](https://user-images.githubusercontent.com/365683/153220726-b5df80ff-e520-402f-bb03-65ad00974747.png)
```
root@pihole:/# pihole status web
53
root@pihole:/#
```

**Comment by yubiuser** [comment] 2022-02-10 05:14
The reason it works now is https://github.com/pi-hole/FTL/pull/1264

This is not in master yet, but development only.

**Comment by juampe** [comment] 2022-06-12 10:05
Solved in master

**Closed by juampe** 2022-06-12 10:05 UTC
